#!/usr/bin/env python3
"""Generate psp/trig_df_table_data.hpp: sin/cos at the nodes a = k / 256 (k = 0..NODE_MAX)
as double-float {hi, lo} pairs.  hi = binary32(v), lo = binary32(v - hi), v = binary64 libm.
The reduced argument of the trig DF fast path is |r| <= 0.86, so NODE_MAX = 221 (221/256 = 0.863)."""
import math
import struct

NODE_MAX = 221


def f32(x):
    return struct.unpack('f', struct.pack('f', x))[0]


def split(v):
    hi = f32(v)
    lo = f32(v - hi)
    return hi, lo


lines = [
    '// Generated by tools/gen_trig_df_table.py -- do not edit.',
    '// sin/cos at a = k / 256 (k = 0..%d) as double-float {hi, lo}; residual < 2^-48 relative.' % NODE_MAX,
    '#pragma once',
    '',
    'namespace th08::psp::sincos_detail',
    '{',
    'struct TrigDfNode',
    '{',
    '    float sinHi;',
    '    float sinLo;',
    '    float cosHi;',
    '    float cosLo;',
    '};',
    'constexpr int kTrigDfNodeMax = %d;' % NODE_MAX,
    'constexpr TrigDfNode kTrigDfNodes[kTrigDfNodeMax + 1] = {',
]
for k in range(NODE_MAX + 1):
    a = k / 256.0
    sh, sl = split(math.sin(a))
    ch, cl = split(math.cos(a))
    def lit(v):
        s = '%.9g' % v
        if not any(c in s for c in '.e'):
            s += '.0'
        return s + 'f'
    lines.append('    {%s, %s, %s, %s}, // k=%d' % (lit(sh), lit(sl), lit(ch), lit(cl), k))
lines += ['};', '} // namespace th08::psp::sincos_detail', '']
open('psp/trig_df_table_data.hpp', 'w').write('\n'.join(lines))
print('wrote psp/trig_df_table_data.hpp', NODE_MAX + 1, 'nodes')
